### ISSUE TITLE
Continue logging errors locally to error_log

### ISSUE THREAD

**Issue by zeman** [MindscapeHQ/raygun4php#101]
The default usage in the Readme disables the local error_log file. We'd like to send errors to Raygun but also send them to the local error_log. Any recommendations or examples on the best way to do this? Be great to add it to the Readme as well.

**Comment by sumitramanga** [comment]
Hi there, I'll be closing this out as this is now a stale Issue.

If anyone is keeping an eye on this Issue, we are happy to re open and discuss if more help us required! Just let us know :) 

Cheers,
Sumitra
