### ISSUE TITLE
Issues when bundled in a phar archive

### ISSUE THREAD

**Issue by halkyon** [MindscapeHQ/raygun4php#103]
First issue: `realpath()` usage does not work with phar, when called on `__DIR__`. I have been running a fork with the following fix to get the class loading to work: https://github.com/halkyon/raygun4php/commit/d74d1765d8421ad39de2a5072d3407dcdef3fc53
Recommended approach would be to go all in with composer PSR-4 autoloading, so these require statements can be removed entirely. This would break the ability to install raygun4php without composer, but I suspect it's not a popular way to install this client.

Second issue: async sending doesn't work, because RaygunClient shells out to `curl` and passes a cert path like `phar:///path/to/cert.crt` which won't work because references to files inside a phar are "virtual" paths, not real filesystem ones. Workaround has to been to set `useAsyncSending` to false which works, because it uses php stream functions that support phar paths. A recommended approach for portability would be to replace the HTTP call code with Guzzle, which also supports sending async.

**Comment by robbieaverill** [comment]
@halkyon there's some WIP for the next major version for using PSR-4 and relying on the composer autoloader. See #105.

**Comment by robbieaverill** [comment]
See #111 for Guzzle

**Comment by GuySartorelli** [comment]
@robbieaverill Did #111 resolve this? I think this issue should be closed.

**Comment by robbieaverill** [comment]
Let's close it under the assumption that it does resolve this, and reopen if necessary.
