### ISSUE TITLE
Add error bundling to help deal with high traffic

### ISSUE THREAD

**Issue by robbieaverill** [MindscapeHQ/raygun4php#112]
Original pull request from #93 had the following points:

Updates
* Add a bundler class which populates an array with incoming messages
* Send a bundle after certain conditions have been met. Either the number of messages in the bundle reaches the maximum bundle size (default 100) or after a time period (default 60s)
* Post bundle to the bundle entries endpoint on the API

@samuel-holt said on the PR: I would be interested in adding this bundling functionality but with a different approach, I think this PR is stale and should be deleted.

This issue can track a future enhancement to re-implement it again.

**Comment by sumitramanga** [comment]
Hi @robbieaverill I'll be closing this out as this is now a stale Issue (per your request)

If anyone is keeping an eye on this Issue, we are happy to re open and discuss! Just let us know :) 

Cheers,
Sumitra
