### ISSUE TITLE
Invalid characters passed for attempted conversion

### ISSUE THREAD

**Issue by takwing** [MindscapeHQ/raygun4php#126]
With php7.4, the error "Invalid characters passed for attempted conversion" is triggered at /mindscape/raygun4php/src/Raygun4php/RaygunMessage.php:

**Comment by robbieaverill** [comment]
Thanks for raising this issue. Do you have a full stack trace available?

**Comment by takwing** [comment]
#0 Raygun4php\RaygunClient::SendError called at [/htdocs/classes/helpers/MyErrorHandler.php:74]
#1 MyErrorHandler::error_handler called at [:0]
#2 ::hexdec called at [/htdocs/lib/Raygun4php/RaygunClient.php:419]
#3 Raygun4php\RaygunClient::Raygun4php\{closure} called at [:0]
#4 ::preg_replace_callback called at [/htdocs/lib/Raygun4php/RaygunClient.php:419]
#5 Raygun4php\RaygunClient::toJsonRemoveUnicodeSequences called at [/htdocs/lib/Raygun4php/RaygunClient.php:324]
#6 Raygun4php\RaygunClient::Send called at [/htdocs/lib/Raygun4php/RaygunClient.php:127]
#7 Raygun4php\RaygunClient::SendException called at [/htdocs/classes/helpers/MyErrorHandler.php:132

**Comment by robbieaverill** [comment]
@takwing can you please provide the version of this package you're using? `composer show mindscape/raygun4php`

**Comment by robbieaverill** [comment]
Nevermind, I can reproduce the error in existing unit tests.

**Comment by robbieaverill** [comment]
You're welcome to propose a backport of that patch to 1.8 if you'd like, I'll release that in 2.0.x however.
