### ISSUE TITLE
"Couldn't send asynchronously" error

### ISSUE THREAD

**Issue by ltachet** [MindscapeHQ/raygun4php#128]
Hi team,

Occasionnaly, our PHP service is wrapping errors with:

```
<br/><br/><strong>Raygun Warning:</strong> Couldn't send asynchronously. Try calling new RaygunClient('apikey', FALSE); to use an alternate sending method, or RaygunClient('key', FALSE, TRUE) to echo the HTTP response<br/><br/>
```

1. Do you know why this is occurring occasionally? We are sending our errors asynchronously to Raygun and would like to continue to do so. [It looks like](https://github.com/vend/raygun4php/blob/daddb63cfc4659312cc44c171662ebf107aa4f2a/src/Raygun4php/RaygunClient.php#L332) a socket connection couldn't be opened, but that's all we know...

2. [Because of this wrapping](https://github.com/vend/raygun4php/blob/daddb63cfc4659312cc44c171662ebf107aa4f2a/src/Raygun4php/RaygunClient.php#L367) from our PHP service, our Go service getting the errors is unable to parse them (it expect some JSON: `Failed to unmarshal json: invalid character '<' looking for beginning of value`). Is there a way to avoid this behaviour?

Thanks for your help!

**Comment by samuel-holt** [comment]
Hi @ltachet,

This string will be appended to the error message if the `$debug` flag is set to true. This is third parameter in the `RaygunClient()` constructor (see the documentation [here](https://github.com/MindscapeHQ/raygun4php/tree/1.8#debugmode-options)). This isn't very clearly described in the docs, but `$debug` should only ever be set to true in a development environment. 

This is also from the older version of the provider (v1.8), I'd recommend updating to the latest version (v2.0) if possible.

Regards,
Sam

**Comment by robbieaverill** [comment]
It sounds as if this is resolved. Please feel free to reopen if not @ltachet! Thanks
