### ISSUE TITLE
Deprecated: Invalid characters passed for attempted conversion, these have been ignored

### ISSUE THREAD

**Issue by chrisd1997** [MindscapeHQ/raygun4php#129]
I'm currently seeing the following message `Deprecated: Invalid characters passed for attempted conversion, these have been ignored in vendor/mindscape/raygun4php/src/Raygun4php/RaygunClient.php on line 438`

PHP Version: **7.3/7.4**
Raygun4PHP Version: **1.8.4**

Please let me know if you require any further details.

**Comment by robbieaverill** [comment]
Hey @chrisd1997, would you like to try the 2.0.x release line?

**Comment by robbieaverill** [comment]
Please try the 2.0.x release line and reopen if it's still an issue there
