### ISSUE TITLE
UTF-8 encoding not working on v1.8 for php 5.3+

### ISSUE THREAD

**Issue by acanuto** [MindscapeHQ/raygun4php#139]
UTF-8 encoding not working on my end every time I send and error/ exception it removes all special characters

**Comment by robbieaverill** [comment]
Hi @acanuto, can you please provide some steps to reproduce?

**Comment by acanuto** [comment]
@robbieaverill thanks for the quick reply, here goes the code block I'm using

`require_once  "vendor/raygun4php/src/Raygun4php/RaygunClient.php";

$client = new \Raygun4php\RaygunClient("API TOKEN REMOVED");
$name = "É";

try {
    throw new Exception("Name: " .  $name);
} catch (Exception $exception) {
    $client->SendException($exception);
}`

**Comment by acanuto** [comment]
Added **setlocale(LC_CTYPE, 'pt_PT');**

`    function toJsonRemoveUnicodeSequences($struct) {
	  setlocale(LC_CTYPE, 'pt_PT');
      return preg_replace_callback("/\\\\u([a-f0-9]{4})/", function($matches){ return iconv('UCS-4LE','UTF-8',pack('V', hexdec("U$matches[1]"))); }, json_encode($struct));
    }`

It's now working like it should, going to close the issue =)
