### ISSUE TITLE
Async auto-off on windows?

### ISSUE THREAD

**Issue by CostaC** [MindscapeHQ/raygun4php#39]
The docs state "For Windows, false is the only effective option available due to a bug in SSL sending on IIS with certain versions of PHP. Passing in true will do nothing on this platform."

But I run Apache on my local Windows machine not IIS.  Is this bug an IIS bug or a Windows bug?  (the code check the OS string, not the web server)

I use lots of SSL api calls from my code so I know SSL works on Windows + Apache. 

I haven't tried Raygun yet. I'd just like some clarification on the nature of the bug (I'm currently exploring error loggers).  Thanks.

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
