### ISSUE TITLE
.gitignore comment issue

### ISSUE THREAD

**Issue by mrardon** [MindscapeHQ/raygun4php#53]
.gitignore files are allowed to have comments however they must be at the beginning of the line not after pattern that is ignored. 

The issue is here: 
https://github.com/MindscapeHQ/raygun4php/blob/af96ad3273a8f8ea3b415a13925a256ad442b94c/.gitignore#L109

We recently switched to using satis and this issue came up when trying to pull down the code for this. It consistently died with the following exception:

```
Dumping 'mindscape/raygun4php-1.2.1.0'.
  - Installing mindscape/raygun4php (1.2.1)
    Cloning e65e879e6e2ecc16208cbaab53a74154f6f11017




  [ErrorException]                    
  preg_match(): Unknown modifier 'a'  



Exception trace:
 () at /vendor/composer/composer/src/Composer/Package/Archiver/BaseExcludeFilter.php:62
```

Info on .gitignore is here: http://git-scm.com/book/en/Git-Basics-Recording-Changes-to-the-Repository#Ignoring-Files

The reason it is dying with that exception is due to how composer processes ignore files, namely it makes patterns to ignore and follows the standard set forward in the previous document. So for each line of .gitignore it makes a regex pattern using the delimiter of #

So if the pattern for the line referenced above is invalid because it is not ignored (required # at the beginning of the line):
`#(?=[^\.])Generated_Code #added for RIA/(?=[^\.])Silverlight projects(?=$|/)#`

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
