### ISSUE TITLE
Error: E_NOTICE: Undefined index: rguserid 

### ISSUE THREAD

**Issue by sjparkinson** [MindscapeHQ/raygun4php#64]
We recently got the following error from our raygun integration:

https://app.raygun.io/dashboard/1d7ikw/errors/726210665

Using version 1.6.0 of the client.

See: [RaygunClient.php line 225](https://github.com/MindscapeHQ/raygun4php/blob/v1.6.0/src/Raygun4php/RaygunClient.php#L225)

Anything we should be worried about? I've permanently ignored the error for now.

**Comment by fundead** [comment]
Thanks for reporting this one - we're investigating and will let you know the results.

Regards,

Callum Gavin
Mindscape Limited

**Comment by sjparkinson** [comment]
Hi @fundead, any update on this?

**Comment by fundead** [comment]
Cheers for your patience on this one, this provider's next in line for a release and this issue should be solved in that (there's a guard for this condition above). Release shouldn't be too far away.
