### ISSUE TITLE
Several cookies being set with identical keys

### ISSUE THREAD

**Issue by sjparkinson** [MindscapeHQ/raygun4php#66]
I'm finding the client is setting several cookies with the same key:

![screen shot 2015-04-21 at 3 47 57 pm](https://cloud.githubusercontent.com/assets/51677/7254918/cecbbf08-e83d-11e4-8a98-6bb6853f0e65.png)

**Comment by fundead** [comment]
Thanks for this report, we'll look into getting this tidied up in the next release.

**Comment by pjaybell** [comment]
We've come across this issue on our system as well. A `rgisanonymous` cookie is created for every page the user visits on our site. 

We've had issues with customers being logged out after a days use and I've managed to replicate this by viewing 200 different pages in Firefox 51.0 using Selenium IDE. It looks like it has hit the max limit of cookies for the browser causing them to be logged out.

Sorry for jumping on this thread but didn't want to log a duplicate issue.

**Comment by pjaybell** [comment]
Can I ask why you are closing this @sjparkinson ? Is it being fixed / superseded / ignored?

**Comment by sjparkinson** [comment]
Just pruning all my really old issues.

**Comment by pjaybell** [comment]
Does that mean you'll re-log this? This was still an issue 25th Jan 2017

**Comment by fundead** [comment]
Just an update on this one - we're going to have a team member take another look at reproducing the behavior with an eye towards getting a fix out the door ASAP.

**Comment by pjaybell** [comment]
thanks @fundead - if you need any help reproducing it give me a shout

**Comment by BenjaminHarding** [comment]
Letting you know that we've fixed this bug in v1.8.0 of the provider. PR #92

Thanks for reporting this. Any other issues just let us know :)
