### ISSUE TITLE
Installation instructions recommend dev-master version

### ISSUE THREAD

**Issue by dominics** [MindscapeHQ/raygun4php#78]
The 'createapp' step over on Raygun.io recommends installing this library with:

```
{
  "require": {
    "mindscape/raygun4php": "dev-master"
  }
}
```

But including the library like that will break if this repo ever breaks BC (e.g. when a 2.0 version is prepared). It'd be better to recommend a version constraint like `~1.6`.

Also, using `dev-master` leads to [problems with `minimum-stability`](https://igor.io/2013/02/07/composer-stability-flags.html). If you actually do want people running against a branch rather than a series of tags, the correct approach is to use [aliases](https://getcomposer.org/doc/articles/aliases.md). That way, when master goes from being 1.x to 2.0-prerelease/alpha, those following the 1.x-dev branch will correctly stop following master.

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
