### ISSUE TITLE
Incorrect no. params passed to ErrorException

### ISSUE THREAD

**Issue by phptek** [MindscapeHQ/raygun4php#83]
PHP 5.5.9 / Ubuntu 14.04 / RayGun4PHP dev-master (9252af27) used in SilverStripe's own RayGun module.

PHP's `ErrorException` class's constructor expects 6 params, but `RayGunClient` sends only 5 via a call to `BuildMessage()` in `RayGunClient.php:74`, which, ironically is reported within raygun.io itself :-P

**Comment by robbieaverill** [comment]
@phptek looks like all of the exception's constructor arguments are optional - are you still experiencing this?

**Comment by phptek** [comment]
Um no. That was 3 years ago! I use Sentry now.

**Comment by robbieaverill** [comment]
Ha, ok. Given that it looks ok in theory, I’ll close this issue for now.
