### ISSUE TITLE
Potential breaking change for rhumsaa/uuid

### ISSUE THREAD

**Issue by hootener** [MindscapeHQ/raygun4php#86]
I'm getting the following error using Raygun4php:

> Fatal error: Class 'Raygun4Php\Rhumsaa\Uuid\Uuid' not found in <path truncated>vendor/mindscape/raygun4php/src/Raygun4php/RaygunClient.php on line 161

It looks like recently the author decided to re-namespace the package. From https://github.com/ramsey/uuid:

> NOTICE: Formerly known as rhumsaa/uuid, The package and namespace names have changed to ramsey/uuid and Ramsey\Uuid, respectively.

It looks like this may be a breaking change for Raygun4Php since the library for generating UUIDs has been renamespaced out from under it.

However, upon investigating the source of raygun4php more, it looks like the Uuid file is bundled with the soruce as opposed to being loaded via composer, which is what I initially could lead to this error. If that's not the case, though, what could be leading to this error so far down in the Raygun4php source?

Thanks.

**Comment by fundead** [comment]
Thanks for alerting us to this. For this library the Uuid class is vendored in Raygun4php/Uuid.php and placed beneath its own namespace `Raygun4Php\Rhumsaa\Uuid`, and I would have hoped that this would have been enough to prevent a collision (we had a commit to add that custom namespace a couple years ago to avoid this issue).

I take it you're using Composer - in your `vendor/autoload.php` is it loading another library that also depends on ramsey/uuid or Rhumsaa/uuid?

**Comment by hootener** [comment]
> For this library the Uuid class is vendored in Raygun4php/Uuid.php and placed beneath its own namespace Raygun4Php\Rhumsaa\Uuid, and I would have hoped that this would have been enough to prevent a collision

Exactly. I think this should avoid any collision problems, as well. 

> I take it you're using Composer - in your vendor/autoload.php is it loading another library that also depends on ramsey/uuid or Rhumsaa/uuid?

I see no other dependencies on Rhumsaa/uuid in my source, but upon digging into it more I'm not quite sure how Uuid can be causing issues in raygun4php since, like you've said, you've namespaced it yourselves to prevent specifically these kinds of issues. 

I'm going to go ahead and close this ticket until I can find more definitive proof that the error is actually due to Uuid as it is included with raygun4php. 

Thanks for the input.
